#!/usr/bin/env perl

# Primes p such that p^2 = (a+b+c)*b + 1 for some primitive Pythagorean triple (a,b,c).
# https://oeis.org/A393809

# Known terms:
#   7, 19, 89, 337, 1693, 2311, 17299, 297991, 744199, 9122471, 11244967, 17451491, 23442299, 105929209, 584136199, 716797951

use strict;
use warnings;

# Require the modules (Install via `cpan Math::Prime::Util Math::GMPz`)
use Math::Prime::Util qw(is_prime gcd);
use Math::GMPz;

# Generates primes p such that p^2 = (a+b+c)*b + 1 for a PPT.
sub generate_pythagorean_primes_gmp {
    my ($from, $max_x) = @_;

    print "Searching for primes generated by PPTs up to x = $max_x...\n";
    print "-" x 50 . "\n";

   # my $x_plus_y = Math::GMPz::Rmpz_init();
    my $v1 = Math::GMPz::Rmpz_init();
    my $v2 = Math::GMPz::Rmpz_init();
    my $root = Math::GMPz->new(0);

    for my $x ($from .. $max_x) {

        # Enforce parity rule to ensure the triple is primitive
        my $start_y = ($x % 2 == 0) ? 1 : 2;

        for (my $y = $start_y; $y < $x; $y += 2) {

            # x and y must be coprime
            next unless gcd($x, $y) == 1;

            # Cast x and y to GMP objects for the heavy polynomial math.
            # We use overloaded operators for readability; GMPz handles them efficiently.
            my $x_plus_y = $x + $y;

            # ---------------------------------------------------------
            # Case 1: b is the even leg
            # Factored form: p^2 = 4*x^2*y*(x+y) + 1
            # ---------------------------------------------------------
            Math::GMPz::Rmpz_set_ui($v1, $x);
            Math::GMPz::Rmpz_mul_ui($v1, $v1, $x);
            Math::GMPz::Rmpz_mul_ui($v1, $v1, 4);
            Math::GMPz::Rmpz_mul_ui($v1, $v1, $y);
            Math::GMPz::Rmpz_mul_ui($v1, $v1, $x_plus_y);
            Math::GMPz::Rmpz_add_ui($v1, $v1, 1);

            # Rmpz_perfect_square_p is wildly fast at rejecting non-squares
            if (Math::GMPz::Rmpz_perfect_square_p($v1)) {
                Math::GMPz::Rmpz_sqrt($root, $v1);
                if (Math::GMPz::Rmpz_probab_prime_p($root,22)) {
                    print "Found p = $root\t (Even leg, x=$x, y=$y)\n";
                }
            }

            # ---------------------------------------------------------
            # Case 2: b is the odd leg
            # Factored form: p^2 = 2*x*(x-y)*(x+y)^2 + 1
            # ---------------------------------------------------------
            my $x_minus_y = $x - $y;
            Math::GMPz::Rmpz_set_ui($v2, $x);
            Math::GMPz::Rmpz_mul_ui($v2, $v2, $x_minus_y);
            Math::GMPz::Rmpz_mul_ui($v2, $v2, $x_plus_y);
            Math::GMPz::Rmpz_mul_ui($v2, $v2, $x_plus_y);
            Math::GMPz::Rmpz_mul_ui($v2, $v2, 2);
            Math::GMPz::Rmpz_add_ui($v2, $v2, 1);

            if (Math::GMPz::Rmpz_perfect_square_p($v2)) {
                Math::GMPz::Rmpz_sqrt($root, $v2);

                if (Math::GMPz::Rmpz_probab_prime_p($root,22)) {
                    print "Found p = $root\t (Odd leg,  x=$x, y=$y)\n";
                }
            }
        }
    }
}

# Execute the search.
generate_pythagorean_primes_gmp(1, 716797951*10);

__END__
Searching for primes generated by PPTs up to x = 7167979510...
--------------------------------------------------
Found p = 7  (Even leg, x=2, y=1)
Found p = 19     (Even leg, x=3, y=2)
Found p = 89     (Even leg, x=6, y=5)
Found p = 337    (Even leg, x=13, y=8)
Found p = 1693   (Even leg, x=33, y=14)
Found p = 2311   (Even leg, x=34, y=21)
Found p = 17299  (Even leg, x=155, y=18)
Found p = 297991     (Odd leg,  x=440, y=139)
Found p = 744199     (Even leg, x=610, y=377)
Found p = 9122471    (Even leg, x=2166, y=1285)
Found p = 11244967   (Even leg, x=2738, y=1099)
Found p = 23442299   (Even leg, x=3355, y=2198)
Found p = 17451491   (Odd leg,  x=4956, y=4621)
Found p = 105929209  (Even leg, x=8514, y=3281)
Found p = 716797951  (Even leg, x=22880, y=7957)
Found p = 2026129753     (Even leg, x=26774, y=26749)
Found p = 2284079491     (Even leg, x=29469, y=26726)
Found p = 1312382287     (Even leg, x=30989, y=10744)
Found p = 584136199      (Odd leg,  x=38824, y=38081)
Found p = 1379597959     (Even leg, x=39894, y=6451)
Found p = 1384117799     (Even leg, x=40310, y=6321)
Found p = 4299982849     (Even leg, x=46368, y=28657)
Found p = 10723729381    (Even leg, x=65533, y=55370)
Found p = 11309910407    (Even leg, x=67946, y=55921)
